### ISSUE TITLE
Selection window not scrollable

### ISSUE THREAD

**Issue by trashie65** [Julian-adv/WildDivide#3]
Hi after updating my custom nodes & comfyui to the latest the wildDivide selection window now does not scroll so you can not select all of the items only the ones shown... in the attached picture you can see the the list only shows some on the list (the bottom half of the list)
![wild](https://github.com/user-attachments/assets/15818f4f-0dbc-48a2-a7be-b592187e4bd9)

The edit window is also the same (no scroll) so again you cant view all in the list

![wild2](https://github.com/user-attachments/assets/624d53e5-1d77-4493-9e47-c60a232ea653)

**Comment by Julian-adv** [comment]
Fixed

**Comment by trashie65** [comment]
The scrolling now works thank you,  but the selection window is to high and goes under the comfy top menu bar so you still cant see all the list. ie disable, random. 
![wild3](https://github.com/user-attachments/assets/63f5c823-09f9-464e-92d5-a3e69448db1f)

**Comment by Julian-adv** [comment]
Fixed

**Comment by trashie65** [comment]
Thank you very much all seems ok now the problems i had are now gone, thanks again for a super node ill be using this alot as it makes using wildcards so much easyer

**Comment by trashie65** [comment]
Hi another issue i have now is the same same before where the selection window has no scroll and to high up the page but only for the fist option "background"... please can you fix

![wild4](https://github.com/user-attachments/assets/b6b770b7-2303-4d6f-9e14-95eb99d8bb26)

**Comment by Julian-adv** [comment]
Hmmm... would you install latest version and try it? I updated some.

**Comment by trashie65** [comment]
thank you all good now

**Comment by trashie65** [comment]
sorry about this but new bug found, when gragging workflow window the options that have been selected (even if set to random, appear on the screen)...
![wild5](https://github.com/user-attachments/assets/c73f26be-1fd2-41a6-9d8c-d8314097bdd7)
