### ISSUE TITLE
Generator Node not updating

### ISSUE THREAD

**Issue by trashie65** [Julian-adv/WildDivide#4]
hi the generator node as stopped updating since the last update, you can add/delete a slot and then you have to restart comfyui to get the slot in the node list
![wild6](https://github.com/user-attachments/assets/7302bc70-66be-4a76-9762-5bca42809421)
![wild7](https://github.com/user-attachments/assets/45e73176-34e0-41e6-8e02-fba3be2bf982)

**Comment by trashie65** [comment]
after restart of comfy
![wild8](https://github.com/user-attachments/assets/3ee716ca-cc99-475f-96a1-3a41e48805ec)

**Comment by trashie65** [comment]
also dragging slots to a new postion does not work anymore

**Comment by Julian-adv** [comment]
Fixed the bug node is not updating after adding slot.

**Comment by trashie65** [comment]
thank you

**Comment by trashie65** [comment]
Hay sorry about this but that did not work still the same issue see vid's 

https://github.com/user-attachments/assets/0cd6dcb2-7aa3-4384-b8f0-9ad30dd4d9b4


https://github.com/user-attachments/assets/58c73793-cf02-47d3-bd3f-ef742e4cfda6

Next the images show after comfy restart (note the new postion of arty which is now correct and the slot test is now in the list)

**Comment by trashie65** [comment]
![wild10](https://github.com/user-attachments/assets/b6045a32-ef49-4a02-a7e6-6895db099d9c)
![wild11](https://github.com/user-attachments/assets/7a7042f0-ff9f-4910-8412-5f4418b81f28)

**Comment by Julian-adv** [comment]
@trashie65 Would you try again with latest version?

**Comment by Julian-adv** [comment]
I added version number at bottom of the node. currently 0.3.0
![스크린샷 2024-12-13 113001](https://github.com/user-attachments/assets/1307fa98-b063-435f-a81b-28fc4a6d8ad8)

**Comment by trashie65** [comment]
ok ill try again

**Comment by trashie65** [comment]
for some reason its not updating.. im geting this error in the console:
Update check done....
Update custom node 'Wild Divide'
Update: ['https://github.com/Julian-adv/WildDivide']
Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin
  stderr: 'error: Your local changes to the following files would be overwritten by merge:'
CUSTOM NODE PULL: Fail

**Comment by trashie65** [comment]
OK uninstalled node re-installed via manager now working as it should, but not sure if it will update via manager till there is a new update... lol. will let you know afer next update.. thanks again for a great node system, im in the middle of trainsfering all my wildcards to this system.. hope more people get to use this but i thank at the moment there must be only me as no one else is finding bugs.. (chief tester... lol)

**Comment by Julian-adv** [comment]
@trashie65 thanks chief tester! 😄

**Comment by trashie65** [comment]
lol your welcome.. any idea about hat error with updating

**Comment by Julian-adv** [comment]
Error message above means you modified some files

**Comment by trashie65** [comment]
mmmm strange i havent modified anything.. ill see how it goes

**Comment by Julian-adv** [comment]
In that case 'git reset --hard' will reset your folder to clean state. Then 'git pull' to update it.

**Comment by trashie65** [comment]
Ok thanks ill give that a try

**Comment by trashie65** [comment]
Where do i run 'git reset --hard'

**Comment by Julian-adv** [comment]
@trashie65 in `ComfyUI/custom_nodes/WildDivide` directory

**Comment by ebonydad** [comment]
I am having a similar issue. I am trying to create my own YAML file to I can create custom prompts, but for some reason the "Wild Prompt Generator" Node is not populating. 
![Screenshot 2024-12-18 191918](https://github.com/user-attachments/assets/646e51c5-fd1b-4d18-b3ca-8029a4a4fd23)
I have no idea why. I have reinstalled the Node, but no luck.

Any ideas?

**Comment by trashie65** [comment]
If the Prompt Generator" Node is not populating then there is probably an error in your yaml file, check the comfy console for any errors. im also just going to raise a new issue log as my version v0.5.0 the add slo or add group button now does not work

**Comment by Julian-adv** [comment]
Would you try again? I fixed some.

**Comment by Julian-adv** [comment]
@ebonydad It will create `m.yaml` in `ComfyUI/custom_nodes/WildDivide/wildcards` in first run. Is it there?

**Comment by trashie65** [comment]
> Would you try again? I fixed some.

will do now

**Comment by trashie65** [comment]
> Would you try again? I fixed some.

all working now thank you
